添加直连、全局模式小角标
yichengchen/clashX pull request #939
Opened 2022-07-08 06:10 UTC by ResistanceTo

切换全局和直连模式时，图标显示不同小角标

2022-07-13 01:16 UTC, yichengchen commented
感觉需要一个开关

2022-07-13 01:18 UTC, yichengchen requested changes

2022-07-13 01:18 UTC, yichengchen commented on ClashX/AppDelegate.swift
>      @IBAction func actionSwitchProxyMode(_ sender: NSMenuItem) {
启动默认的图片？

2022-07-13 01:18 UTC, yichengchen commented on ClashX/AppDelegate.swift
> +            if let image = NSImage(contentsOfFile: imagePath!),
if let imagePath = imagePath, let image = NSImage(contentsOfFile: imagePath) {

2022-07-13 02:15 UTC, ResistanceTo commented on ClashX/AppDelegate.swift
>      @IBAction func actionSwitchProxyMode(_ sender: NSMenuItem) {
我忽略这一点了，测试的时候我就给切换回规则模式了，我空闲时间再想个好的办法。

2022-07-24 13:02 UTC, bug0error commented
如何实现自定义规则，机场的链接更新时会重置规则，在config.yaml直接写规则也不行，如何设置一些默认的规则呢

2022-07-25 01:45 UTC, ResistanceTo commented
先关闭pr，开发测试完毕再提交，防止作为issue

2022-07-25 01:45 UTC, closed without merging